### ISSUE TITLE
my_super_model.h5 cannot be loaded

### ISSUE THREAD

**Issue by basheewang** [remi2257/sudoku-solver#1]
1. First, the model name is not match in the main py file, which is 'model/my_model.h5' and the real file name is 'model/my_super_model.h5'.
2. Second, even to use -mp to overwrite the model name, there is an error pop out as below, please kindly help or fix.

Using TensorFlow backend.
Traceback (most recent call last):
  File "sudoku_solver_main.py", line 109, in <module>
    main_process()
  File "sudoku_solver_main.py", line 92, in main_process
    args, model = setting_recup()
  File "sudoku_solver_main.py", line 84, in setting_recup
    model = load_model(args.model_path)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\sequential.py", line 301, in from_config
    custom_objects=custom_objects)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\utils\generic_utils.py", line 149, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\engine\base_layer.py", line 1179, in from_config
    return cls(**config)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\layers\convolutional.py", line 484, in __init__
    **kwargs)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\layers\convolutional.py", line 117, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\initializers.py", line 515, in get
    return deserialize(identifier)
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\initializers.py", line 510, in deserialize
    printable_module_name='initializer')
  File "C:\Coeus\github\pyenv\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform

**Comment by remi2257** [comment]
Hi,

I firstly renamed all "my_super_model" to "my_model" in 3b39b86d4aed41252e430b471ff33fb6aed6e28c. It solve your first issue

In a second time, I change an `import keras` to `import tensorflow.keras`. It has been done in the commit e50525c2f92e08d0ee83c6c07df01416daf7c5ea. It solves your second point :smile: 

Thx for your contribution
